"""
Django settings for latigue project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os.path
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charger les variables d'environnement depuis .env
env_path = BASE_DIR / '.env'
if env_path.exists():
    load_dotenv(env_path, override=True)  # override=True pour forcer le rechargement
    print(f"[OK] Fichier .env charge depuis: {env_path}")
else:
    # Essayer aussi .env.secrets si .env n'existe pas
    env_secrets_path = BASE_DIR / '.env.secrets'
    if env_secrets_path.exists():
        load_dotenv(env_secrets_path, override=True)
        print(f"[OK] Fichier .env.secrets charge depuis: {env_secrets_path}")
    else:
        print("[WARNING] Aucun fichier .env trouve")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'
print(f"[DEBUG CHECK] DJANGO_DEBUG from env: {os.environ.get('DJANGO_DEBUG', 'False')}")
print(f"[DEBUG CHECK] DEBUG value: {DEBUG}")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-r5e^_f5z5g-l+dy-$p%2n9a%+9*vq@1j(2e!2v=ee8&q!!kuq$')

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.herokuapp.com',
    'latigue-9570ef49bb0e.herokuapp.com',
    'postgres-u67346.vm.elestio.app',  # URL Elestio
    'cicd-xbhk2-u67346.vm.elestio.app',  # Ancien CI/CD Elestio
    'customdocker-u67346.vm.elestio.app',  # Custom Docker Compose Elestio
    'bolibana.net',
    'www.bolibana.net',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    "django.contrib.staticfiles",
    'django.contrib.sitemaps',  # Pour le sitemap.xml SEO
    # AWS S3 pour le stockage externe des médias
    'storages',
    "portfolio",
    'livereload',
    'blog',
    'ckeditor',
    'ckeditor_uploader',
    'services',
    'formations',
    'chatbot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'livereload.middleware.LiveReloadScript',  # Desactive temporairement
]

ROOT_URLCONF = 'latigue.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'blog.context_processors.post_processor',
                'portfolio.context_processors.seo_context',  # Pour Google Analytics et autres variables SEO
            ],
        },
    },
]

WSGI_APPLICATION = 'latigue.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if DEBUG:
    # SQLite pour le developpement local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # PostgreSQL pour la production
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600
        )
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Cache configuration
# Utilise le cache en mémoire pour le développement et un cache Redis/Memcached en production
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# En production, vous pouvez utiliser Redis :
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
#     }
# }

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    # other static file directories...
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ==================================================
# CONFIGURATION AWS S3 POUR LES FICHIERS MÉDIAS
# ==================================================
# Configuration AWS S3
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'eu-west-3')  # Région par défaut

# Configuration conditionnelle du stockage
# Permet de forcer l'utilisation de S3 même en local pour les tests
USE_S3_STORAGE = os.environ.get('USE_S3_STORAGE', 'False').strip().lower() == 'true'

# Debug: Vérifier si les variables sont chargées (uniquement en développement)
if DEBUG:
    print(f"[DEBUG] S3 - AWS_ACCESS_KEY_ID: {'Defini' if AWS_ACCESS_KEY_ID else 'Non defini'}")
    print(f"[DEBUG] S3 - AWS_SECRET_ACCESS_KEY: {'Defini' if AWS_SECRET_ACCESS_KEY else 'Non defini'}")
    print(f"[DEBUG] S3 - AWS_STORAGE_BUCKET_NAME: {'Defini' if AWS_STORAGE_BUCKET_NAME else 'Non defini'}")
    print(f"[DEBUG] S3 - USE_S3_STORAGE: {USE_S3_STORAGE}")

AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com' if AWS_STORAGE_BUCKET_NAME else None
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',  # Cache de 24h
}
AWS_DEFAULT_ACL = None  # Laisse S3 gérer les ACL ou défini sur 'public-read' si nécessaire
AWS_QUERYSTRING_AUTH = True  # Pour générer des URLs signées pour les fichiers médias privés

if DEBUG and not USE_S3_STORAGE:
    # Stockage local en développement (par défaut)
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:
    # Stockage S3 en production ou si USE_S3_STORAGE=True
    # Vérifier que les variables AWS sont configurées
    if not AWS_ACCESS_KEY_ID or not AWS_SECRET_ACCESS_KEY or not AWS_STORAGE_BUCKET_NAME:
        if DEBUG:
            # En développement, utiliser le stockage local si S3 n'est pas configuré
            DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
            MEDIA_URL = '/media/'
            MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
            print("[WARNING] ATTENTION: Variables AWS S3 non configurees. Utilisation du stockage local.")
        else:
            # En production, c'est une erreur critique
            raise ValueError("Variables AWS S3 requises en production: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_STORAGE_BUCKET_NAME")
    else:
        DEFAULT_FILE_STORAGE = 'latigue.storage_backends.MediaStorage'
        MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'

# Configuration CKEditor
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"

# Configuration Cloudinary (remplacé par S3 - conservé pour référence)
# CLOUDINARY_STORAGE = {
#     'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
#     'API_KEY': os.environ.get('CLOUDINARY_API_KEY', ''),
#     'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', ''),
# }

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Google Analytics ID (optionnel - à configurer dans les variables d'environnement)
# Exemple: GOOGLE_ANALYTICS_ID=G-XXXXXXXXXX
GOOGLE_ANALYTICS_ID = os.environ.get('GOOGLE_ANALYTICS_ID', None)
WHITENOISE_ROOT = os.path.join(BASE_DIR, 'staticfiles')
WHITENOISE_MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}

# ======================================================================
# EMAIL
# ======================================================================
# En développement : on affiche les emails dans la console pour éviter
# les erreurs SMTP (et pour ne pas utiliser de vraies identifiants).
# En production : on utilise SMTP avec des variables d'environnement.
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    # En développement, utiliser un email par défaut
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@djimiga.com')
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
    # Email par défaut pour l'expéditeur (doit être le même que EMAIL_HOST_USER pour Gmail)
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
    
# Email de destination pour les messages de contact
CONTACT_EMAIL = os.environ.get('CONTACT_EMAIL', EMAIL_HOST_USER if not DEBUG else 'contact@djimiga.com')

# ======================================================================
# PARAMÈTRES DE SÉCURITÉ SSL
# ======================================================================

# Configuration de la redirection HTTPS
if DEBUG:
    # Configuration pour le développement local
    SECURE_SSL_REDIRECT = False
    SECURE_PROXY_SSL_HEADER = None
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SECURE_REFERRER_POLICY = None
    SECURE_CROSS_ORIGIN_OPENER_POLICY = None
    SECURE_CROSS_ORIGIN_EMBEDDER_POLICY = None
else:
    # Configuration pour la production (Heroku)
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 an
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_REFERRER_POLICY = 'same-origin'
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
    SECURE_CROSS_ORIGIN_EMBEDDER_POLICY = 'require-corp'

# Paramètres de cookies sécurisés (communs aux deux environnements)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Protection contre le clickjacking
X_FRAME_OPTIONS = 'DENY'

# Protection contre le sniffing de contenu
SECURE_CONTENT_TYPE_NOSNIFF = True

# Protection XSS
SECURE_BROWSER_XSS_FILTER = True

# Configuration pour servir les fichiers médias en production
if not DEBUG:
    WHITENOISE_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    WHITENOISE_MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ======================================================================
# CSRF TRUSTED ORIGINS (pour nginx reverse proxy)
# ======================================================================
CSRF_TRUSTED_ORIGINS = [
    'https://postgres-u67346.vm.elestio.app',
    'https://bolibana.net',
    'https://www.bolibana.net',
]

# ======================================================================
# LOGGING CONFIGURATION
# ======================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}